server:
  port: 8090

spring:
  application:
    name: gateway

zuul:
  routes:
    salesmen:
      path: /demo/service/**
      serviceId: demo-service
    soapUI:
      path: /soapUI/service/**
      serviceId: soapUI-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/